// Generated by view binder compiler. Do not edit!
package com.example.thesistest.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.RelativeLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.thesistest.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityMainBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final TextView dontHaveAccount;

  @NonNull
  public final ImageView ejeepImage;

  @NonNull
  public final EditText emailInput;

  @NonNull
  public final TextView forgotPasswordText;

  @NonNull
  public final Button loginBtn;

  @NonNull
  public final EditText passwordInput;

  @NonNull
  public final RelativeLayout relativeLayout;

  @NonNull
  public final CheckBox rememberCheckbox;

  private ActivityMainBinding(@NonNull RelativeLayout rootView, @NonNull TextView dontHaveAccount,
      @NonNull ImageView ejeepImage, @NonNull EditText emailInput,
      @NonNull TextView forgotPasswordText, @NonNull Button loginBtn,
      @NonNull EditText passwordInput, @NonNull RelativeLayout relativeLayout,
      @NonNull CheckBox rememberCheckbox) {
    this.rootView = rootView;
    this.dontHaveAccount = dontHaveAccount;
    this.ejeepImage = ejeepImage;
    this.emailInput = emailInput;
    this.forgotPasswordText = forgotPasswordText;
    this.loginBtn = loginBtn;
    this.passwordInput = passwordInput;
    this.relativeLayout = relativeLayout;
    this.rememberCheckbox = rememberCheckbox;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.dont_have_account;
      TextView dontHaveAccount = ViewBindings.findChildViewById(rootView, id);
      if (dontHaveAccount == null) {
        break missingId;
      }

      id = R.id.ejeep_image;
      ImageView ejeepImage = ViewBindings.findChildViewById(rootView, id);
      if (ejeepImage == null) {
        break missingId;
      }

      id = R.id.email_input;
      EditText emailInput = ViewBindings.findChildViewById(rootView, id);
      if (emailInput == null) {
        break missingId;
      }

      id = R.id.forgot_password_text;
      TextView forgotPasswordText = ViewBindings.findChildViewById(rootView, id);
      if (forgotPasswordText == null) {
        break missingId;
      }

      id = R.id.login_btn;
      Button loginBtn = ViewBindings.findChildViewById(rootView, id);
      if (loginBtn == null) {
        break missingId;
      }

      id = R.id.password_input;
      EditText passwordInput = ViewBindings.findChildViewById(rootView, id);
      if (passwordInput == null) {
        break missingId;
      }

      RelativeLayout relativeLayout = (RelativeLayout) rootView;

      id = R.id.remember_checkbox;
      CheckBox rememberCheckbox = ViewBindings.findChildViewById(rootView, id);
      if (rememberCheckbox == null) {
        break missingId;
      }

      return new ActivityMainBinding((RelativeLayout) rootView, dontHaveAccount, ejeepImage,
          emailInput, forgotPasswordText, loginBtn, passwordInput, relativeLayout,
          rememberCheckbox);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
