// Generated by view binder compiler. Do not edit!
package com.example.thesistest.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.FrameLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.thesistest.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentEditBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final EditText FirstName;

  @NonNull
  public final EditText LastName;

  @NonNull
  public final Button updateBtn;

  private FragmentEditBinding(@NonNull FrameLayout rootView, @NonNull EditText FirstName,
      @NonNull EditText LastName, @NonNull Button updateBtn) {
    this.rootView = rootView;
    this.FirstName = FirstName;
    this.LastName = LastName;
    this.updateBtn = updateBtn;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentEditBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentEditBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_edit, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentEditBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.FirstName;
      EditText FirstName = ViewBindings.findChildViewById(rootView, id);
      if (FirstName == null) {
        break missingId;
      }

      id = R.id.LastName;
      EditText LastName = ViewBindings.findChildViewById(rootView, id);
      if (LastName == null) {
        break missingId;
      }

      id = R.id.update_btn;
      Button updateBtn = ViewBindings.findChildViewById(rootView, id);
      if (updateBtn == null) {
        break missingId;
      }

      return new FragmentEditBinding((FrameLayout) rootView, FirstName, LastName, updateBtn);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
